; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32 @ 6.5.0
; board = esp32-c3-devkitm-1 
framework = arduino
monitor_speed = 115200
;upload_speed = 2000000
lib_deps = 
	bblanchon/ArduinoJson@^6.21.3

; board_build.flash_mode = dio
; board_upload.flash_size = 4MB

; choose the FS
board_build.filesystem = littlefs

; enable custom partition table
board_build.partitions = partitions.csv
build_type = debug
monitor_filters = default, esp32_exception_decoder

[env:seeed_xiao_esp32s3]
board = seeed_xiao_esp32s3
build_flags =
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBLDC_UART_TX_PIN=43
	-DBLDC_UART_RX_PIN=44
	-DBLDC_UART_OE_PIN=-1
monitor_dtr = 0
monitor_rts = 0
build_src_filter =
	+<*>
	-<main_led.cpp>

[env:seeed_xiao_esp32s3_led]
board = seeed_xiao_esp32s3
build_flags =
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
monitor_dtr = 0
monitor_rts = 0
build_src_filter =
	+<*>
	-<main_bldc.cpp>

[env:nodemcu-32s]
board = nodemcu-32s
build_flags =
	-DBLDC_UART_OE_PIN=19
build_src_filter =
	+<*>
	-<main_led.cpp>

[env:nodemcu-32s_led]
board = nodemcu-32s
build_src_filter =
	+<*>
	-<main_led.cpp>
